all_book = [
# {'title': 'Маг-крестоносец. Маг и кошка', 'author': 'Сташеф', 'isbns': ['5-17-022745-0', '5-9577-1188-8'], 'only_isbn': False},
{'title': 'Слимперия', 'author': 'Бабкин', 'isbns': ['5-93556-229-4'], 'only_isbn': False},
{'title': 'Иное небо. Наша старая добрая фантастика', 'author': None, 'isbns': ['978-5-389-14930-4'], 'only_isbn': False},
{'title': 'Старая Контра', 'author': 'Марушкин', 'isbns': ['978-5-699-20106-8'], 'only_isbn': False},
{'title': 'Закон девяток', 'author': 'Гудкайнд', 'isbns': None, 'only_isbn': False},
{'title': 'Разлученные души', 'author': 'Гудкайнд', 'isbns': None, 'only_isbn': False},
# {'title': 'Мы. Бич Божий', 'author': 'Замятин', 'isbns': ['978-5-389-20387-7'], 'only_isbn': True},
# {'title': 'Пожиратель душ. Об ангелах демонах и потусторонних кошмарах', 'author': 'Каттнер Генри', 'isbns': ['978-5-389-22220-5'], 'only_isbn': False},
# {'title': 'Глаз Дракона', 'author': 'Маккефри', 'isbns': ['5-699-07904-1'], 'only_isbn': False},
# {'title': 'Дельфины Перна', 'author': 'Маккефри', 'isbns': ['5-699-10394-5'], 'only_isbn': False},
# {'title': 'Драконий родич', 'author': 'Маккефри', 'isbns': ['5-699-10083-0'], 'only_isbn': False},
# {'title': 'Драконье пламя', 'author': 'Маккефри', 'isbns': ['978-5-699-30664-0'], 'only_isbn': False},
# {'title': 'Кровь драконов', 'author': 'Маккефри', 'isbns': ['5-699-16054-X'], 'only_isbn': False},
# {'title': 'Мастер-арфист', 'author': 'Маккефри', 'isbns': ['5-699-15085-4'], 'only_isbn': False},
# {'title': 'Небеса Перна', 'author': 'Маккефри', 'isbns': ['5-699-15972-X'], 'only_isbn': False},
# {'title': 'Хроники Перна: Первое падение', 'author': 'Маккефри', 'isbns': ['5-699-13482-4'], 'only_isbn': False},
# {'title': '1984. Скотный двор. Да здравствует фикус!', 'author': 'Оруэлл', 'isbns': ['978-5-17-164053-8'], 'only_isbn': True},
# {'title': 'Занимательная наука. Физика. Механика. Астрономия', 'author': 'Перельман', 'isbns': ['978-5-389-24268-5'], 'only_isbn': False},
{'title': 'Душа Бога. Том 1', 'author': 'Перумов', 'isbns': ['978-5-04-110924-0'], 'only_isbn': False},
{'title': 'Пирамиды', 'author': 'Пратчетт', 'isbns': ['5-699-16835-4'], 'only_isbn': False},
{'title': 'Последний герой. Сказание о Плоском мире', 'author': 'Пратчетт', 'isbns': ['5-699-17413-3', '978-5-699-17413-3'], 'only_isbn': False},
{'title': 'Ночная стража', 'author': 'Пратчетт', 'isbns': ['978-5-699-52239-2'], 'only_isbn': False},
{'title': 'Незримые Академики', 'author': 'Пратчетт', 'isbns': ['978-5-699-69984-1'], 'only_isbn': False},
{'title': 'Наука Плоского мира. Книга 3. Часы Дарвина', 'author': 'Пратчетт', 'isbns': ['978-5-699-89838-1'], 'only_isbn': False},
# {'title': 'О дивный новый мир. Остров. Возвращение в дивный новый мир', 'author': 'Хаксли', 'isbns': ['978-5-17-160649-7'], 'only_isbn': True},
{'title': 'Последний мятеж', 'author': 'Щепетов Сергей', 'isbns': ['5-9717-0089-8'], 'only_isbn': False},
# {'title': 'Кровь заката', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
# {'title': 'Довод королей', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
# {'title': 'Башня ярости. Чёрные маки', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
# {'title': 'Башня ярости. Всходы ветра', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
{'title': 'Три мушкетера', 'author': 'Дюма', 'isbns': ['978-5-389-19881-4'], 'only_isbn': True},
{'title': 'Двадцать лет спустя', 'author': 'Дюма', 'isbns': ['978-5-389-21145-2'], 'only_isbn': True},
{'title': 'Виконт де Бражелон, или Еще десять лет спустя', 'author': 'Дюма', 'isbns': ['978-5-389-24464-1'], 'only_isbn': True},
{'title': 'Бесконечная Земля', 'author': 'Пратчетт', 'isbns': ['978-5-699-72378-2'], 'only_isbn': False},

{'title': 'Острые края', 'author': 'Аберкромби', 'isbns': ['978-5-04-118152-9'], 'only_isbn': False},
{'title': 'Лучше подавать холодным', 'author': 'Аберкромби', 'isbns': ['978-5-04-090300-9'], 'only_isbn': False},
# {'title': 'Море Осколков', 'author': 'Аберкромби', 'isbns': ['978-5-04-122888-0'], 'only_isbn': True},
# {'title': 'Полкороля', 'author': 'Аберкромби', 'isbns': ['978-5-04-157042-2'], 'only_isbn': False},

{'title': 'HHhH', 'author': 'Бине', 'isbns': ['978-5-86471-701-1'], 'only_isbn': False},

# {'title': 'Волки Кальи', 'author': 'Кинг', 'isbns': ['978-5-17-133881-7'], 'only_isbn': True},
{'title': 'Песнь Сюзанны', 'author': 'Кинг', 'isbns': ['978-5-17-133029-3'], 'only_isbn': True},

# {'title': '', 'author': '', 'isbns': [''], 'only_isbn': True},
# {'title': '', 'author': 'Кинг', 'isbns': [''], 'only_isbn': True},

# {'title': '', 'author': '', 'isbns': [''], 'only_isbn': False},
    ]

all_book2 = [
{'title': 'Маг-крестоносец. Маг и кошка', 'author': 'Сташеф', 'isbns': ['5-17-022745-0', '5-9577-1188-8'], 'only_isbn': False},
{'title': 'Слимперия', 'author': 'Бабкин', 'isbns': ['5-93556-229-4'], 'only_isbn': False},
{'title': 'Иное небо', 'author': 'Наша старая добрая фантастика', 'isbns': ['978-5-389-14930-4'], 'only_isbn': False},
{'title': 'Старая Контра', 'author': 'Марушкин', 'isbns': ['978-5-699-20106-8'], 'only_isbn': False},
{'title': 'Разлученные души', 'author': 'Гудкайнд', 'isbns': None, 'only_isbn': False},
{'title': 'Закон девяток', 'author': 'Гудкайнд', 'isbns': None, 'only_isbn': False},
{'title': 'Мы. Бич Божий', 'author': 'Замятин', 'isbns': ['978-5-389-20387-7'], 'only_isbn': True},
{'title': 'Пожиратель душ. Об ангелах демонах и потусторонних кошмарах', 'author': 'Каттнер Генри', 'isbns': ['978-5-389-22220-5'], 'only_isbn': False},
{'title': 'Глаз Дракона', 'author': 'Маккефри', 'isbns': ['5-699-07904-1'], 'only_isbn': False},
{'title': 'Дельфины Перна', 'author': 'Маккефри', 'isbns': ['5-699-10394-5'], 'only_isbn': False},
{'title': 'Драконий родич', 'author': 'Маккефри', 'isbns': ['5-699-10083-0'], 'only_isbn': False},
{'title': 'Драконье пламя', 'author': 'Маккефри', 'isbns': ['978-5-699-30664-0'], 'only_isbn': False},
{'title': 'Кровь драконов', 'author': 'Маккефри', 'isbns': ['5-699-16054-X'], 'only_isbn': False},
{'title': 'Мастер-арфист', 'author': 'Маккефри', 'isbns': ['5-699-15085-4'], 'only_isbn': False},
{'title': 'Небеса Перна', 'author': 'Маккефри', 'isbns': ['5-699-15972-X'], 'only_isbn': False},
{'title': 'Хроники Перна: Первое падение', 'author': 'Маккефри', 'isbns': ['5-699-13482-4'], 'only_isbn': False},
{'title': '1984. Скотный двор. Да здравствует фикус!', 'author': 'Оруэлл', 'isbns': ['978-5-17-164053-8'], 'only_isbn': True},
{'title': 'Занимательная наука. Физика. Механика. Астрономия', 'author': 'Перельман', 'isbns': ['978-5-389-24268-5'], 'only_isbn': False},
{'title': 'Душа Бога. Том 1', 'author': 'Перумов', 'isbns': ['978-5-04-110924-0'], 'only_isbn': False},
{'title': 'Пирамиды', 'author': 'Пратчетт', 'isbns': ['5-699-16835-4'], 'only_isbn': False},
{'title': 'Последний герой. Сказание о Плоском мире', 'author': 'Пратчетт', 'isbns': ['5-699-17413-3', '978-5-699-17413-3'], 'only_isbn': False},
{'title': 'Ночная стража', 'author': 'Пратчетт', 'isbns': ['978-5-699-52239-2'], 'only_isbn': False},
{'title': 'Незримые Академики', 'author': 'Пратчетт', 'isbns': ['978-5-699-69984-1'], 'only_isbn': False},
{'title': 'Наука Плоского мира. Книга 3. Часы Дарвина', 'author': 'Пратчетт', 'isbns': ['978-5-699-89838-1'], 'only_isbn': False},
{'title': 'О дивный новый мир. Остров. Возвращение в дивный новый мир', 'author': 'Хаксли', 'isbns': ['978-5-17-160649-7'], 'only_isbn': True},
{'title': 'Последний мятеж', 'author': 'Щепетов Сергей', 'isbns': ['5-9717-0089-8'], 'only_isbn': False},
{'title': 'Кровь заката', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
{'title': 'Довод королей', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
{'title': 'Башня ярости. Чёрные маки', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
{'title': 'Башня ярости. Всходы ветра', 'author': 'Камша', 'isbns': None, 'only_isbn': False},
{'title': 'Три мушкетера', 'author': 'Дюма', 'isbns': ['978-5-389-19881-4'], 'only_isbn': True},
{'title': 'Двадцать лет спустя', 'author': 'Дюма', 'isbns': ['978-5-389-21145-2'], 'only_isbn': True},
{'title': 'Виконт де Бражелон, или Еще десять лет спустя', 'author': 'Дюма', 'isbns': ['978-5-389-24464-1'], 'only_isbn': True},
{'title': 'Бесконечная Земля', 'author': 'Пратчетт', 'isbns': ['978-5-699-72378-2'], 'only_isbn': False},

{'title': 'Острые края', 'author': 'Аберкромби', 'isbns': ['978-5-04-118152-9'], 'only_isbn': False},
{'title': 'Лучше подавать холодным', 'author': 'Аберкромби', 'isbns': ['978-5-04-090300-9'], 'only_isbn': False},
# {'title': 'Полкороля', 'author': 'Аберкромби', 'isbns': ['978-5-04-157042-2'], 'only_isbn': False},

{'title': 'HHhH', 'author': 'Бине', 'isbns': ['978-5-86471-701-1'], 'only_isbn': False},

# {'title': 'Волки Кальи', 'author': 'Кинг', 'isbns': ['978-5-17-133881-7'], 'only_isbn': True},
{'title': 'Песнь Сюзанны', 'author': 'Кинг', 'isbns': ['978-5-17-133029-3'], 'only_isbn': True},
    ]
